apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: maven
      image: maven:3.6.3-jdk-8
      imagePullPolicy: Always # use cache or pull image for agent
      resources:  # limits the resources your build contaienr
    - name: docker
      image: docker:18.06.1
      imagePullPolicy: Always